apiVersion: v1
entries:
  derolas-subgraph:
  - apiVersion: v2
    appVersion: 0.0.20
    created: "2025-08-11T13:12:47.111164996Z"
    description: A Helm chart for Kubernetes
    digest: bab65b22a7ab58afdc4b76cd244f4e9358c7dce47ef0406d475a9bc2e0fc0ce6
    name: derolas-subgraph
    type: application
    urls:
    - https://stationsstation.github.io/derolas_subgraph/charts/derolas-subgraph-0.1.0.tgz
    version: 0.1.0
  derolas_subgraph:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-11T13:12:47.11156248Z"
    description: A Helm chart for Kubernetes
    digest: c4167f7dbb2c490d16701fe402bc6ca7e1e85242b5f91c59cb0564f311388025
    name: derolas_subgraph
    type: application
    urls:
    - https://stationsstation.github.io/derolas_subgraph/charts/derolas_subgraph-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-11T13:12:47.110639022Z"
