name: publish
"on":
  push:
    tags:
      - v*
jobs:
  build-docker:
    env:
      DOCKER_BUILDKIT: 1
      RELEASE_VERSION: 0.0.4
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            args: "--target x86_64-unknown-linux-gnu"
            docker_platform: linux/amd64
            tag_suffix: linux-amd64
          - os: ubuntu-22.04
            args: "--target aarch64-unknown-linux-gnu"
            docker_platform: linux/arm64
            tag_suffix: linux-arm64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push multi-arch
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
            ${{ env.IMAGE_NAME }}:latest
